question_data:[
{"type": "multiple", "difficulty": "medium", "category": "Mythology",
     "question": "Which of the following is not one of the Greek Fates?",
     "correct_answer": "Narcissus",
     "incorrect_answers": ["Clotho", "Atropos", "Lachesis"]},
    {"type": "multiple", "difficulty": "medium", "category": "Mythology",
     "question": "Which of these Roman gods doesn&#039;t have a counterpart in Greek mythology?",
     "correct_answer": "Janus",
     "incorrect_answers": ["Vulcan", "Juno", "Mars"]},
    {"type": "multiple", "difficulty": "easy", "category": "Mythology",
     "question": "In most traditions, who was the wife of Zeus?",
     "correct_answer": "Hera",
     "incorrect_answers": ["Aphrodite", "Athena", "Hestia"]},
    {"type": "boolean", "difficulty": "easy", "category": "Mythology",
     "question": "A wyvern is the same as a dragon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Mythology",
     "question": "Hel was the daughter of which Norse Mythological figure?",
     "correct_answer": "Loki",
     "incorrect_answers": ["Thor", "Odin", "Balder"]},
    {"type": "boolean", "difficulty": "medium", "category": "Mythology",
     "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Mythology",
     "question": "The Hippogriff, not to be confused with the Griffon, is a magical creature with the front half of an eagle, and the back half of what?",
     "correct_answer": "A Horse",
     "incorrect_answers": ["A Dragon", "A Tiger", "A Lion"]},
    {"type": "multiple", "difficulty": "medium", "category": "Mythology",
     "question": "A minotaur is half human half what?",
     "correct_answer": "Bull",
     "incorrect_answers": ["Cow", "Horse", "Eagle"]},
    {"type": "multiple", "difficulty": "medium", "category": "Mythology",
     "question": "Neptune&#039;s greek name was...",
     "correct_answer": "Poseidon",
     "incorrect_answers": ["Ares", "Zeus", "Apollo"]},
    {"type": "multiple", "difficulty": "easy", "category": "Mythology",
     "question": "Which Greek &amp; Roman god was known as the god of music, truth and prophecy, healing, the sun and light, plague, poetry, and more?",
     "correct_answer": "Apollo",
     "incorrect_answers": ["Aphrodite", "Artemis", "Athena"]}]
